name: Dependency Check

concurrency:
  group: dependency-check-${{ github.head_ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update_dependency:
    name: Check dependency
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Near Update dependency
        id: near-update-dependency
        run: nix develop -c 'update-dependency' near

      - name: Create Pull Request
        if: failure() && steps.near-update-dependency.outcome != 'success'
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: Cargo.toml
          reviewers: yanganto
          base: main
          branch: near-update
          branch-suffix: timestamp
          title: "Near Dependency Update"
          commit-message: "automated dependency update"

      - name: Update dependency
        id: solana-update-dependency
        run: nix develop -c 'update-dependency' solana

      - name: Create Pull Request
        if: failure() && steps.solana-update-dependency.outcome != 'success'
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: Cargo.toml
          reviewers: yanganto
          base: main
          branch: near-update
          branch-suffix: timestamp
          title: "Solana Dependency Update"
          commit-message: "automated dependency update"
