name: Near

concurrency:
  group: near-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # Temp disable clippy due to rustc with near macro incompatiable issue
      # - name: Clippy
      #   run: nix develop -c cargo clippy -p near-atomic-swap
      #   env:
      #     RUST_BACKTRACE: 1

      - name: WASM Build
        working-directory: ./near
        run: nix develop -c cargo build -p near-atomic-swap --target=wasm32-unknown-unknown --release

      - name: Native Build & Test
        working-directory: ./near
        run: |
          nix develop -c cargo build -p near-atomic-swap
          nix develop -c cargo test -p near-atomic-swap

      - name: Integratiom Test
        working-directory: ./near
        run: nix develop -c cargo test -p near-atomic-swap --examples -- --nocapture
