name: Near

concurrency:
  group: near-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_RUST_2018: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Clippy
        run: nix develop -c cargo clippy -p near
        env:
          RUST_BACKTRACE: 1

      - name: Build
        run: nix develop -c cargo build -p near

      - name: Test
        run: nix develop -c cargo test -p near
