name: Typo

concurrency:
  group: typo-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  typo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args:  typos-cli

      - name: Check typo
        run: typos
